### ISSUE TITLE
can you consider adding documentation what this software is doing and how it can be used?

### ISSUE THREAD

**Issue by matkoniecz** [edouardhue/commons-downloader#1]

**Comment by edouardhue** [comment]
Hi. I don't expect to maintain this tool any more, but I added a quick description and a readme.

**Comment by matkoniecz** [comment]
Thanks!

**Comment by matkoniecz** [comment]
If you are curious why I ended here - it is linked from https://commons.wikimedia.org/wiki/Commons:Tools#Download_media
